using System;
using System.Data;
using System.Linq;
using System.Windows;
using System.Windows.Data;
using System.Windows.Controls;
using System.Windows.Media.Imaging;

using static CourseWork.DBController;

namespace CourseWork.Pages.UserPart
{
    public partial class Documents : Page
    {
        int clientId;
        public Documents(int clientId)
        {
            this.clientId = clientId;
            InitializeComponent();

            LoadPassports();
            LoadVisas();
        }

        private void LoadPassports()
        {
            PassportsTable.AutoGeneratedColumns +=
                (s, e) =>
                {
                    PassportsTable.Columns[2].Width = 105;
                    (PassportsTable.Columns[3] as DataGridTextColumn).Binding = new Binding("IssueDate")
                    {
                        StringFormat = "yyyy-MM-dd"
                    };
                    (PassportsTable.Columns[4] as DataGridTextColumn).Binding = new Binding("IssueDate")
                    {
                        StringFormat = "yyyy-MM-dd"
                    };
                };
            PassportsTable.AutoGeneratedColumns +=
                (s, e) => Additionals.ContolsSettings.ColumnsNaming(s, e, "", "", "Данні", "Дата видачі", "Дата зпливу");
            PassportsTable.AutoGeneratedColumns +=
                (s, e) => Additionals.ContolsSettings.ColumnsVisibility(s, e, Visibility.Hidden, Visibility.Hidden);

            DataTable table = GetTable($"SELECT * FROM [dbo].[Passport] WHERE ClientId = {clientId}");

            if(table.Rows.Count > 0)
            {
                PassportsTable.ItemsSource = table.DefaultView;

                PassportsTable.IsReadOnly = true;
            }
            else
            {
                PassportsTable.Visibility = Visibility.Hidden;
                NoPassports.Visibility = Visibility.Visible;
            }
        }

        private void LoadVisas()
        {
            DataTable table = GetTable($"SELECT * FROM [dbo].[Visa] WHERE PassportId IN (SELECT PassportId FROM [dbo].[Passport] WHERE ClientId = {clientId})");

            if(table.Rows.Count > 0)
            {
                VisaTable.ItemsSource = table.DefaultView;

                VisaTable.IsReadOnly = true;
            }
            else
            {
                VisaTable.Visibility = Visibility.Hidden;
                NoVisas.Visibility = Visibility.Visible;
            }
        }
    }
}
