using System;
using System.Data;
using System.Linq;
using System.Windows;
using System.Windows.Data;
using System.Windows.Controls;
using System.Windows.Media.Imaging;

using static CourseWork.DBController;

namespace CourseWork.Pages.TourPart
{
    public partial class CityPage : Page
    {
        public CityPage()
        {
            InitializeComponent();

            //Edit
            CityTable.RowEditEnding +=
                (s, e) =>
                {
                    MessageBox.Show("Edited");
                };
            //loading
            CityTable.LoadingRow +=
                (s, e) =>
                {
                    DataRowView row = e?.Row?.Item as DataRowView;

                    if (row != null)
                    {
                        row.Row["BitmapFrame"] = DataConverter.GetImageFromByteArray(GetObject<byte[]>($"SELECT Image FROM [dbo].[City] WHERE CityId = {row.Row["CityId"]}"));
                    }
                };
            //unloading
            CityTable.UnloadingRow +=
                (s, e) =>
                {
                    DataRowView row = e?.Row?.Item as DataRowView;
                    if (row != null)
                        row.Row["BitmapFrame"] = null;
                    GC.Collect();
                };
            //Columns generating
            CityTable.AutoGeneratedColumns +=
                (s, e) =>
                {
                    var columns = CityTable.Columns;
                    columns[0].Header = "Id";
                    columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[1].Header = "Назва";
                    columns[1].Width = 120;
                    columns[2].Header = "Країна";
                    columns[2].Width = 120;
                    columns[3].Header = "У використанні";
                    columns[3].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[4].Header = "Зображення";
                    columns[4].Width = 150;
                };
            //Column generated
            CityTable.AutoGeneratingColumn +=
                (s, e) =>
                {
                    if ((string)e.Column.Header == "BitmapFrame")
                    {
                        Binding binding = new Binding("BitmapFrame");
                        binding.Mode = BindingMode.TwoWay;
                        FrameworkElementFactory image = new FrameworkElementFactory(typeof(Image));
                        image.SetValue(Image.SourceProperty, binding);
                        DataTemplate cellTemplate = new DataTemplate();
                        cellTemplate.VisualTree = image;
                        DataGridTemplateColumn templateColumn = new DataGridTemplateColumn();
                        templateColumn.Header = "BitmapFrame";
                        templateColumn.CellTemplate = cellTemplate;
                        e.Column = templateColumn;
                    }
                };

            LoadCities();
        }

        public void LoadCities()
        {
            DataTable table = GetTable("SELECT ct.CityId, ct.CityName, cntry.NameUa, ct.InUse FROM[dbo].[City] as ct JOIN[dbo].[Country] as cntry ON ct.CountryId = cntry.CountryId");
            table.Columns.Add("BitmapFrame", typeof(BitmapFrame));

            CityTable.ItemsSource = table.DefaultView;

            CityTable.CanUserDeleteRows = false;
        }
    }
}
