using System;
using System.Data;
using System.Linq;
using System.Windows;
using System.Windows.Data;
using System.Windows.Controls;
using System.Windows.Media.Imaging;

using static CourseWork.DBController;

namespace CourseWork.Pages.TourPart
{
    public partial class RoutePage : Page
    {
        public RoutePage()
        {
            InitializeComponent();

            #region Countries table events
            //Edit
            RouteTable.RowEditEnding +=
                (s, e) =>
                {
                    MessageBox.Show("Edited");
                };
            //Columns generating
            RouteTable.AutoGeneratedColumns +=
                (s, e) =>
                {
                    var columns = RouteTable.Columns;
                    columns[0].Header = "Id";
                    columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[1].Header = "Назва";
                    columns[1].Width = 150;
                    columns[2].Header = "Ціна";
                    columns[2].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[3].Header = "Опис";
                    columns[3].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                };
            //Selection
            RouteTable.SelectionChanged +=
                (s, e) =>
                {
                    if ((e.AddedItems as object[]).FirstOrDefault().GetType() == typeof(DataRowView))
                    {
                        var row = (e.AddedItems as object[]).First() as DataRowView;
                        var items = row.Row.ItemArray;
                        Title.Text = (string)items[1];
                        GlobalInfo.Text = $"Id: {items[0]}\nЦіна: {items[2]}$\nОпис: {items[3]}";

                        Details.IsEnabled = true;
                    }
                };
            //Double click
            RouteTable.MouseDoubleClick +=
                (s, e) =>
                {
                    OpenDetails(s, null);
                };
            #endregion

            LoadRoutes();
        }

        public void LoadRoutes()
        {
            DataTable table = GetTable("SELECT RouteId, Name, Price, Description FROM [dbo].[Route]");

            RouteTable.ItemsSource = table.DefaultView;

            RouteTable.CanUserDeleteRows = false;
        }

        private void OpenDetails(object sender, RoutedEventArgs e)
        {
            var o = RouteTable.SelectedItem;
            if (o != null && o.GetType() == typeof(DataRowView))
            {
                var a = RouteTable.SelectedItem as DataRowView;
                MainWindow.WindowFrame.Navigate(new RouteInfoPage((int)a.Row.ItemArray[0]));
            }
        }
    }
}
