using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Data;

using static CourseWork.DBController;

namespace CourseWork.Pages.TourPart
{
    /// <summary>
    /// Interaction logic for TourEnumeration.xaml
    /// </summary>
    public partial class TourEnumeration : Page
    {
        public TourEnumeration()
        {
            InitializeComponent();
            InitTravelWay();
            InitAdditionalType();
            InitMealType();
        }

        public void InitTravelWay()
        {
            DataTable table = GetTable("SELECT * FROM [dbo].[TravelWay]");

            TravelWay.AutoGeneratedColumns +=
                (s, e) =>
                {
                    TravelWay.Columns[0].Visibility = Visibility.Hidden;
                    TravelWay.Columns[1].Header = "Тип ";
                    TravelWay.Columns[1].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    TravelWay.Columns[2].Header = "У використанні ";
                    TravelWay.Columns[2].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                };

            TravelWay.ItemsSource = table.DefaultView;

            TravelWay.AutoGenerateColumns = true;
            TravelWay.CanUserResizeColumns = false;
            TravelWay.CanUserDeleteRows = false;

            TravelWay.RowEditEnding += (s, e) => throw new Exception();
        }

        public void InitAdditionalType()
        {
            DataTable table = GetTable("SELECT * FROM [dbo].[AdditionalType]");

            AdditionalType.AutoGeneratedColumns +=
                (s, e) =>
                {
                    AdditionalType.Columns[0].Visibility = Visibility.Hidden;
                    AdditionalType.Columns[1].Header = "Тип ";
                    AdditionalType.Columns[1].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    AdditionalType.Columns[2].Header = "У використанні ";
                    AdditionalType.Columns[2].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                };

            AdditionalType.ItemsSource = table.DefaultView;

            AdditionalType.AutoGenerateColumns = true;
            AdditionalType.CanUserResizeColumns = false;
            AdditionalType.CanUserDeleteRows = false;

            AdditionalType.RowEditEnding += (s, e) => throw new Exception();
        }

        public void InitMealType()
        {
            DataTable table = GetTable("SELECT MealTypeId, Abbreviation, Type, InUse, Description FROM [dbo].[MealType]");

            MealType.AutoGeneratedColumns +=
                (s, e) =>
                {
                    MealType.Columns[0].Visibility = Visibility.Hidden;
                    MealType.Columns[1].Header = "Абревіатура ";
                    MealType.Columns[1].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    MealType.Columns[2].Header = "Тип ";
                    MealType.Columns[2].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    MealType.Columns[3].Header = "У використанні ";
                    MealType.Columns[3].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    MealType.Columns[4].Header = "Опис ";
                    MealType.Columns[4].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                };

            MealType.ItemsSource = table.DefaultView;

            MealType.CanUserDeleteRows = false;

            MealType.RowEditEnding += (s, e) => throw new Exception();
        }
    }
}
