using System;
using System.Data;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media.Imaging;

using static CourseWork.DBController;

namespace CourseWork.Pages.UserPart
{
    /// <summary>
    /// Interaction logic for UserPage.xaml
    /// </summary>
    public partial class UserPage : Page
    {
        public UserPage()
        {
            InitializeComponent();
            LoadUsers();

            UserTable.AutoGeneratedColumns +=
                (s, e) =>
                {
                    var columns = UserTable.Columns;
                    columns[0].Header = "Id";
                    columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[1].Header = "Ім'я";
                    columns[1].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[2].Header = "Прізвище";
                    columns[2].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[3].Header = "По батькові";
                    columns[3].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[4].Header = "Телефон";
                    columns[4].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[5].Header = "Email";
                    columns[5].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[6].Header = "Дата регістрації";
                    columns[6].Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
                    columns[7].Header = "Примітка";
                    columns[7].Width = 100;
                };
            UserTable.AutoGeneratingColumn +=
                (s, e) =>
                {
                    if((string)e.Column.Header == "RegestrationDate")
                    {
                        DataGridTextColumn textClm = new DataGridTextColumn();
                        Binding binding = new Binding("RegestrationDate");
                        binding.StringFormat = "dd-MM-yyyy";
                        textClm.Binding = binding;
                        e.Column = textClm;
                    }
                    else if ((string)e.Column.Header == "ClientId")
                    {
                        DataGridTemplateColumn buttonColumn = new DataGridTemplateColumn();
                        DataTemplate buttonTemplate = new DataTemplate();
                        FrameworkElementFactory buttonFactory = new FrameworkElementFactory(typeof(Button));
                        buttonTemplate.VisualTree = buttonFactory;
                        buttonFactory.AddHandler(Button.ClickEvent, new RoutedEventHandler(InfoButtonClick));
                        buttonFactory.SetValue(ContentProperty, "Інформація");
                        buttonColumn.CellTemplate = buttonTemplate;
                        e.Column = buttonColumn;
                    }
                };
        }

        private void InfoButtonClick(object sender, RoutedEventArgs e)
        {
            MainWindow.WindowFrame.Navigate(new Client((int)(((FrameworkElement)sender).DataContext as DataRowView).Row["ClientID"]));
        }

        public void LoadUsers()
        {
            DataTable table = GetTable("SELECT * FROM [dbo].[Client]");

            UserTable.ItemsSource = table.DefaultView;
            UserTable.IsReadOnly = true;
            UserTable.CanUserDeleteRows = false;
        }
    }
}
